host: "localhost:3000"
user_name: "b50a4f18fcbe97"
password: "fc8c1a2a7199d3"
address: "smtp.mailtrap.io"
domain: "smtp.mailtrap.io"
port: "2525"
mail_default: "noreply@example.com"
mail_to: "to@example.org"
AUTH_SECRET: "\\~u\x87\x10)\x03\xB0<q\xFEy\xE3*\xF3\x18\x9B\xD2\x0E,>\xB9\x15.\x80x\xC1\xC2\xE1j\xE9W"
