link:
  railstutorial: "https://www.railstutorial.org/"
  railstutorial_help: "https://www.railstutorial.org/help"
  railstutorial_book: "https://www.railstutorial.org/book"
  railstutorial_contact: "https://www.railstutorial.org/contact"
  learnenough: "https://www.learnenough.com/"
  screencasts: "https://screencasts.railstutorial.org/"
  rubyonrails: "https://rubyonrails.org/"
