link:
  railstutorial: "https://www.railstutorial.org/"
  railstutorial_help: "https://www.railstutorial.org/help"
  railstutorial_book: "https://www.railstutorial.org/book"
  railstutorial_contact: "https://www.railstutorial.org/contact"
  learnenough: "https://www.learnenough.com/"
  screencasts: "https://screencasts.railstutorial.org/"
  rubyonrails: "https://rubyonrails.org/"
  michaelhartl: "https://www.michaelhartl.com/"
  news_tutorial: "https://news.railstutorial.org/"
user:
  name:
    length:
      maximum: 50
  email:
    length:
      maximum: 255
    VALID_EMAIL_REGEX: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i'
  password:
    length:
      minimum: 6
  avatar:
    gavatar_domain: "https://secure.gravatar.com/avatar/"
    size: 80
check_box: 1
